title: Refi Ahmad Fauzan
description: Portofolio

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml

collections:
  educations:
  certifications:
  abouts:
  skills:
  languages:
  experiences:
  projects: